image:
  file: .gitpod.Dockerfile
checkoutLocation: "."
tasks:
  - name: Clean root and grab useful exercises.
    before: |
      rm -rfv ./{*,.*}
      sudo mv /home/gitpod/docker-exercises/* .

ports:
  - port: 0-9999
    onOpen: notify
